import { Alert, AlertType, AlertCategory, AlertStatus } from '../entities/Alert';

export const alertSeeds: Partial<Alert>[] = [
  // Critical Alerts
  {
    alert_type: AlertType.CRITICAL,
    category: AlertCategory.HARDWARE,
    title: 'High CPU Temperature on GPU Server',
    description: 'GPU server RBT-B1-S002 is running at 78°C, exceeding critical threshold of 75°C. Immediate cooling attention required.',
    server_id: 'RBT-B1-S002',
    rack_id: 'RBT-B1',
    threshold_value: 75.0,
    current_value: 78.2,
    status: AlertStatus.ACTIVE,
  },
  {
    alert_type: AlertType.CRITICAL,
    category: AlertCategory.HARDWARE,
    title: 'Server Hardware Failure',
    description: 'NAS server RBT-B2-S002 has experienced a hardware failure. Multiple disk errors detected.',
    server_id: 'RBT-B2-S002',
    rack_id: 'RBT-B2',
    threshold_value: 0,
    current_value: 1,
    status: AlertStatus.ACTIVE,
  },
  {
    alert_type: AlertType.CRITICAL,
    category: AlertCategory.NETWORK,
    title: 'Network Connectivity Lost',
    description: 'Proxy server RBT-C2-S002 has lost network connectivity. Unable to reach management interface.',
    server_id: 'RBT-C2-S002',
    rack_id: 'RBT-C2',
    threshold_value: 1,
    current_value: 0,
    status: AlertStatus.ACTIVE,
  },
  
  // Warning Alerts
  {
    alert_type: AlertType.WARNING,
    category: AlertCategory.HARDWARE,
    title: 'High Memory Usage on Database Server',
    description: 'Database server RBT-A1-S002 memory usage has reached 92%, approaching critical threshold.',
    server_id: 'RBT-A1-S002',
    rack_id: 'RBT-A1',
    threshold_value: 90.0,
    current_value: 92.3,
    status: AlertStatus.ACTIVE,
  },
  {
    alert_type: AlertType.WARNING,
    category: AlertCategory.ENVIRONMENT,
    title: 'Elevated Rack Temperature',
    description: 'Rack RBT-A3 temperature has increased to 24.5°C, above normal operating range.',
    rack_id: 'RBT-A3',
    threshold_value: 24.0,
    current_value: 24.5,
    status: AlertStatus.ACKNOWLEDGED,
  },
  {
    alert_type: AlertType.WARNING,
    category: AlertCategory.HARDWARE,
    title: 'High Disk Usage on Log Server',
    description: 'Log server RBT-A3-S002 disk usage has reached 87%, cleanup recommended.',
    server_id: 'RBT-A3-S002',
    rack_id: 'RBT-A3',
    threshold_value: 85.0,
    current_value: 87.4,
    status: AlertStatus.ACTIVE,
  },
  {
    alert_type: AlertType.WARNING,
    category: AlertCategory.HARDWARE,
    title: 'CPU Load Above Baseline',
    description: 'Compute node RBT-B1-S001 CPU usage at 78%, significantly above baseline of 60%.',
    server_id: 'RBT-B1-S001',
    rack_id: 'RBT-B1',
    threshold_value: 70.0,
    current_value: 78.1,
    status: AlertStatus.ACTIVE,
  },
  {
    alert_type: AlertType.WARNING,
    category: AlertCategory.NETWORK,
    title: 'High Network Latency',
    description: 'Increased network latency detected between API server and database server.',
    server_id: 'RBT-A2-S002',
    rack_id: 'RBT-A2',
    threshold_value: 50.0,
    current_value: 67.8,
    status: AlertStatus.ACKNOWLEDGED,
  },

  // Info Alerts
  {
    alert_type: AlertType.INFO,
    category: AlertCategory.HARDWARE,
    title: 'Scheduled Maintenance Started',
    description: 'Backup server RBT-A2-S003 has been placed in maintenance mode for scheduled updates.',
    server_id: 'RBT-A2-S003',
    rack_id: 'RBT-A2',
    threshold_value: 0,
    current_value: 1,
    status: AlertStatus.ACTIVE,
  },
  {
    alert_type: AlertType.INFO,
    category: AlertCategory.HARDWARE,
    title: 'Test Server Configuration Update',
    description: 'Test server RBT-C3-S001 configuration has been updated for new testing procedures.',
    server_id: 'RBT-C3-S001',
    rack_id: 'RBT-C3',
    threshold_value: 0,
    current_value: 1,
    status: AlertStatus.ACTIVE,
  },
  {
    alert_type: AlertType.INFO,
    category: AlertCategory.ENVIRONMENT,
    title: 'Power Usage Optimization',
    description: 'Rack RBT-C1 power consumption has been optimized, reducing usage by 8%.',
    rack_id: 'RBT-C1',
    threshold_value: 3000,
    current_value: 2760,
    status: AlertStatus.RESOLVED,
    resolved_at: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },
  {
    alert_type: AlertType.INFO,
    category: AlertCategory.SECURITY,
    title: 'Security Patch Applied',
    description: 'Security patches have been successfully applied to Kubernetes master server.',
    server_id: 'RBT-C1-S001',
    rack_id: 'RBT-C1',
    threshold_value: 0,
    current_value: 1,
    status: AlertStatus.RESOLVED,
    resolved_at: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
  },

  // Resolved Alerts (historical)
  {
    alert_type: AlertType.WARNING,
    category: AlertCategory.HARDWARE,
    title: 'Memory Usage Spike Resolved',
    description: 'Cache server memory usage spike has been resolved through optimization.',
    server_id: 'RBT-A1-S003',
    rack_id: 'RBT-A1',
    threshold_value: 85.0,
    current_value: 67.2,
    status: AlertStatus.RESOLVED,
    resolved_at: new Date(Date.now() - 6 * 60 * 60 * 1000), // 6 hours ago
  },
  {
    alert_type: AlertType.CRITICAL,
    category: AlertCategory.NETWORK,
    title: 'Network Switch Port Failure',
    description: 'Core switch port failure has been resolved by replacing faulty module.',
    rack_id: 'RBT-A1',
    threshold_value: 1,
    current_value: 0,
    status: AlertStatus.RESOLVED,
    resolved_at: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12 hours ago
  },
  {
    alert_type: AlertType.WARNING,
    category: AlertCategory.ENVIRONMENT,
    title: 'Cooling System Maintenance',
    description: 'Scheduled cooling system maintenance completed successfully.',
    rack_id: 'RBT-B2',
    threshold_value: 25.0,
    current_value: 22.8,
    status: AlertStatus.RESOLVED,
    resolved_at: new Date(Date.now() - 24 * 60 * 60 * 1000), // 24 hours ago
  },

  // Additional Active Alerts
  {
    alert_type: AlertType.WARNING,
    category: AlertCategory.HARDWARE,
    title: 'Storage Server Fan Speed High',
    description: 'Storage server RBT-B2-S001 fan speed has increased to 85% due to elevated temperatures.',
    server_id: 'RBT-B2-S001',
    rack_id: 'RBT-B2',
    threshold_value: 80.0,
    current_value: 85.2,
    status: AlertStatus.ACTIVE,
  },
  {
    alert_type: AlertType.INFO,
    category: AlertCategory.SECURITY,
    title: 'Failed Login Attempts',
    description: 'Multiple failed login attempts detected on mail server management interface.',
    server_id: 'RBT-C2-S001',
    rack_id: 'RBT-C2',
    threshold_value: 5,
    current_value: 8,
    status: AlertStatus.ACKNOWLEDGED,
  },
  {
    alert_type: AlertType.WARNING,
    category: AlertCategory.NETWORK,
    title: 'Switch Port Utilization High',
    description: 'Core switch SW-CORE-01 port utilization has reached 87.5%.',
    rack_id: 'RBT-A1',
    threshold_value: 85.0,
    current_value: 87.5,
    status: AlertStatus.ACTIVE,
  },
];