import { NetworkDevice, NetworkDeviceType } from '../entities/NetworkDevice';

export const networkDeviceSeeds: Partial<NetworkDevice>[] = [
  // Core Network Infrastructure
  {
    id: 'SW-CORE-01',
    name: 'Core Switch 1',
    device_type: NetworkDeviceType.SWITCH,
    brand: 'Cisco',
    model: 'Catalyst 9600',
    rack_id: 'RBT-A1',
    management_ip: '10.1.0.10',
    ports_total: 48,
    ports_used: 42,
    vlans: [100, 101, 102, 200, 300, 400, 500, 600, 700, 800],
    status: 'active',
  },
  {
    id: 'SW-CORE-02',
    name: 'Core Switch 2',
    device_type: NetworkDeviceType.SWITCH,
    brand: 'Cisco',
    model: 'Catalyst 9600',
    rack_id: 'RBT-A2',
    management_ip: '10.1.0.11',
    ports_total: 48,
    ports_used: 38,
    vlans: [100, 101, 102, 200, 300, 400, 500, 600, 700, 800],
    status: 'active',
  },
  {
    id: 'RTR-EDGE-01',
    name: 'Edge Router 1',
    device_type: NetworkDeviceType.ROUTER,
    brand: 'Cisco',
    model: 'ISR 4431',
    rack_id: 'RBT-B1',
    management_ip: '10.1.0.1',
    ports_total: 8,
    ports_used: 6,
    vlans: [1, 100],
    status: 'active',
  },
  {
    id: 'RTR-EDGE-02',
    name: 'Edge Router 2',
    device_type: NetworkDeviceType.ROUTER,
    brand: 'Cisco',
    model: 'ISR 4431',
    rack_id: 'RBT-B2',
    management_ip: '10.1.0.2',
    ports_total: 8,
    ports_used: 4,
    vlans: [1, 100],
    status: 'active',
  },

  // Zone Access Switches
  {
    id: 'SW-ZONA-01',
    name: 'Zone A Access Switch 1',
    device_type: NetworkDeviceType.SWITCH,
    brand: 'Cisco',
    model: 'Catalyst 2960-X',
    rack_id: 'RBT-A3',
    management_ip: '10.1.0.20',
    ports_total: 24,
    ports_used: 18,
    vlans: [100, 101, 102, 200],
    status: 'active',
  },
  {
    id: 'SW-ZONA-02',
    name: 'Zone A Access Switch 2',
    device_type: NetworkDeviceType.SWITCH,
    brand: 'Cisco',
    model: 'Catalyst 2960-X',
    rack_id: 'RBT-A4',
    management_ip: '10.1.0.21',
    ports_total: 24,
    ports_used: 16,
    vlans: [100, 101, 102, 200],
    status: 'active',
  },
  {
    id: 'SW-ZONB-01',
    name: 'Zone B Access Switch 1',
    device_type: NetworkDeviceType.SWITCH,
    brand: 'HP',
    model: 'Aruba 2930F',
    rack_id: 'RBT-B3',
    management_ip: '10.1.0.22',
    ports_total: 24,
    ports_used: 20,
    vlans: [400, 500],
    status: 'active',
  },
  {
    id: 'SW-ZONB-02',
    name: 'Zone B Access Switch 2',
    device_type: NetworkDeviceType.SWITCH,
    brand: 'HP',
    model: 'Aruba 2930F',
    rack_id: 'RBT-B4',
    management_ip: '10.1.0.23',
    ports_total: 24,
    ports_used: 14,
    vlans: [400, 500],
    status: 'active',
  },
  {
    id: 'SW-ZONC-01',
    name: 'Zone C Access Switch 1',
    device_type: NetworkDeviceType.SWITCH,
    brand: 'Juniper',
    model: 'EX3400',
    rack_id: 'RBT-C3',
    management_ip: '10.1.0.24',
    ports_total: 24,
    ports_used: 22,
    vlans: [600, 700, 800],
    status: 'active',
  },
  {
    id: 'SW-ZONC-02',
    name: 'Zone C Access Switch 2',
    device_type: NetworkDeviceType.SWITCH,
    brand: 'Juniper',
    model: 'EX3400',
    rack_id: 'RBT-C4',
    management_ip: '10.1.0.25',
    ports_total: 24,
    ports_used: 12,
    vlans: [600, 700, 800],
    status: 'active',
  },

  // Security Appliances
  {
    id: 'FW-PERIMETER-01',
    name: 'Perimeter Firewall 1',
    device_type: NetworkDeviceType.FIREWALL,
    brand: 'Palo Alto',
    model: 'PA-3220',
    rack_id: 'RBT-C1',
    management_ip: '10.1.0.30',
    ports_total: 16,
    ports_used: 8,
    vlans: [1, 100, 999],
    status: 'active',
  },
  {
    id: 'FW-PERIMETER-02',
    name: 'Perimeter Firewall 2',
    device_type: NetworkDeviceType.FIREWALL,
    brand: 'Palo Alto',
    model: 'PA-3220',
    rack_id: 'RBT-C2',
    management_ip: '10.1.0.31',
    ports_total: 16,
    ports_used: 8,
    vlans: [1, 100, 999],
    status: 'active',
  },
  {
    id: 'FW-INTERNAL-01',
    name: 'Internal Firewall 1',
    device_type: NetworkDeviceType.FIREWALL,
    brand: 'FortiGate',
    model: 'FG-200F',
    rack_id: 'RBT-A4',
    management_ip: '10.1.0.32',
    ports_total: 12,
    ports_used: 10,
    vlans: [100, 200, 300, 400, 500],
    status: 'active',
  },

  // Management and Out-of-Band Switches
  {
    id: 'SW-MGMT-01',
    name: 'Management Switch 1',
    device_type: NetworkDeviceType.SWITCH,
    brand: 'Cisco',
    model: 'Catalyst 2960-L',
    rack_id: 'RBT-B4',
    management_ip: '192.168.100.10',
    ports_total: 24,
    ports_used: 20,
    vlans: [999],
    status: 'active',
  },
  {
    id: 'SW-OOB-01',
    name: 'Out-of-Band Switch 1',
    device_type: NetworkDeviceType.SWITCH,
    brand: 'Cisco',
    model: 'Catalyst 2960-CX',
    rack_id: 'RBT-C4',
    management_ip: '192.168.200.10',
    ports_total: 8,
    ports_used: 6,
    vlans: [998],
    status: 'active',
  },
];