import { Server, ServerStatus } from '../entities/Server';

export const serverSeeds: Partial<Server>[] = [
  // Rack RBT-A1 Servers
  {
    id: 'RBT-A1-S001',
    name: 'web-server-prod-01',
    rack_id: 'RBT-A1',
    position: 'U1-U2',
    server_type: 'Web Server',
    operating_system: 'Ubuntu 20.04 LTS',
    brand: 'Dell',
    model: 'PowerEdge R750',
    cpu_specs: 'Intel Xeon Gold 6338 (32 cores)',
    memory_specs: '128 GB DDR4',
    storage_specs: '2x 1TB NVMe SSD',
    ip_address: '10.1.1.100',
    mac_address: 'aa:bb:cc:dd:ee:01',
    vlan_id: 100,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 25.0,
    memory_baseline: 65.0,
    temp_idle: 35.0,
    power_idle: 180,
  },
  {
    id: 'RBT-A1-S002',
    name: 'db-server-prod-01',
    rack_id: 'RBT-A1',
    position: 'U3-U4',
    server_type: 'Database Server',
    operating_system: 'Ubuntu 20.04 LTS',
    brand: 'HP',
    model: 'ProLiant DL380 Gen10',
    cpu_specs: 'Intel Xeon Silver 4214 (24 cores)',
    memory_specs: '256 GB DDR4',
    storage_specs: '4x 2TB SAS',
    ip_address: '10.1.1.101',
    mac_address: 'aa:bb:cc:dd:ee:02',
    vlan_id: 100,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 45.0,
    memory_baseline: 75.0,
    temp_idle: 38.0,
    power_idle: 220,
  },
  {
    id: 'RBT-A1-S003',
    name: 'cache-server-prod-01',
    rack_id: 'RBT-A1',
    position: 'U5-U6',
    server_type: 'Cache Server',
    operating_system: 'CentOS 8',
    brand: 'Cisco',
    model: 'UCS C220 M5',
    cpu_specs: 'Intel Xeon Gold 6248 (20 cores)',
    memory_specs: '64 GB DDR4',
    storage_specs: '2x 500GB NVMe SSD',
    ip_address: '10.1.1.102',
    mac_address: 'aa:bb:cc:dd:ee:03',
    vlan_id: 101,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 15.0,
    memory_baseline: 85.0,
    temp_idle: 33.0,
    power_idle: 150,
  },

  // Rack RBT-A2 Servers
  {
    id: 'RBT-A2-S001',
    name: 'app-server-prod-01',
    rack_id: 'RBT-A2',
    position: 'U1-U2',
    server_type: 'Application Server',
    operating_system: 'CentOS 8',
    brand: 'Cisco',
    model: 'UCS C240 M5',
    cpu_specs: 'Intel Xeon Gold 6248 (40 cores)',
    memory_specs: '192 GB DDR4',
    storage_specs: '6x 1TB SATA',
    ip_address: '10.1.1.103',
    mac_address: 'aa:bb:cc:dd:ee:04',
    vlan_id: 101,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 35.0,
    memory_baseline: 70.0,
    temp_idle: 36.0,
    power_idle: 200,
  },
  {
    id: 'RBT-A2-S002',
    name: 'api-server-prod-01',
    rack_id: 'RBT-A2',
    position: 'U3-U4',
    server_type: 'API Server',
    operating_system: 'Ubuntu 22.04 LTS',
    brand: 'Dell',
    model: 'PowerEdge R640',
    cpu_specs: 'Intel Xeon Gold 6226R (16 cores)',
    memory_specs: '96 GB DDR4',
    storage_specs: '4x 1TB NVMe SSD',
    ip_address: '10.1.1.104',
    mac_address: 'aa:bb:cc:dd:ee:05',
    vlan_id: 101,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 30.0,
    memory_baseline: 60.0,
    temp_idle: 34.0,
    power_idle: 170,
  },
  {
    id: 'RBT-A2-S003',
    name: 'backup-server-01',
    rack_id: 'RBT-A2',
    position: 'U5-U6',
    server_type: 'Backup Server',
    operating_system: 'Ubuntu 20.04 LTS',
    brand: 'HP',
    model: 'ProLiant DL360 Gen10',
    cpu_specs: 'Intel Xeon Silver 4210R (10 cores)',
    memory_specs: '32 GB DDR4',
    storage_specs: '8x 4TB SATA',
    ip_address: '10.1.1.105',
    mac_address: 'aa:bb:cc:dd:ee:06',
    vlan_id: 200,
    status: ServerStatus.MAINTENANCE,
    cpu_baseline: 20.0,
    memory_baseline: 40.0,
    temp_idle: 32.0,
    power_idle: 140,
  },

  // Rack RBT-A3 Servers
  {
    id: 'RBT-A3-S001',
    name: 'monitoring-server-01',
    rack_id: 'RBT-A3',
    position: 'U1-U2',
    server_type: 'Monitoring Server',
    operating_system: 'Ubuntu 22.04 LTS',
    brand: 'Dell',
    model: 'PowerEdge R450',
    cpu_specs: 'Intel Xeon Silver 4314 (16 cores)',
    memory_specs: '64 GB DDR4',
    storage_specs: '4x 2TB NVMe SSD',
    ip_address: '10.1.1.106',
    mac_address: 'aa:bb:cc:dd:ee:07',
    vlan_id: 300,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 20.0,
    memory_baseline: 50.0,
    temp_idle: 31.0,
    power_idle: 130,
  },
  {
    id: 'RBT-A3-S002',
    name: 'log-server-prod-01',
    rack_id: 'RBT-A3',
    position: 'U3-U4',
    server_type: 'Log Server',
    operating_system: 'CentOS 8',
    brand: 'HP',
    model: 'ProLiant DL385 Gen10',
    cpu_specs: 'AMD EPYC 7302P (16 cores)',
    memory_specs: '128 GB DDR4',
    storage_specs: '6x 4TB SATA',
    ip_address: '10.1.1.107',
    mac_address: 'aa:bb:cc:dd:ee:08',
    vlan_id: 300,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 25.0,
    memory_baseline: 55.0,
    temp_idle: 36.0,
    power_idle: 160,
  },

  // Rack RBT-B1 Servers
  {
    id: 'RBT-B1-S001',
    name: 'compute-node-01',
    rack_id: 'RBT-B1',
    position: 'U1-U4',
    server_type: 'Compute Node',
    operating_system: 'Ubuntu 20.04 LTS',
    brand: 'Dell',
    model: 'PowerEdge R7525',
    cpu_specs: '2x AMD EPYC 7742 (128 cores)',
    memory_specs: '512 GB DDR4',
    storage_specs: '8x 2TB NVMe SSD',
    ip_address: '10.1.2.100',
    mac_address: 'bb:cc:dd:ee:ff:01',
    vlan_id: 400,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 60.0,
    memory_baseline: 80.0,
    temp_idle: 42.0,
    power_idle: 350,
  },
  {
    id: 'RBT-B1-S002',
    name: 'gpu-server-01',
    rack_id: 'RBT-B1',
    position: 'U5-U8',
    server_type: 'GPU Server',
    operating_system: 'Ubuntu 22.04 LTS',
    brand: 'NVIDIA',
    model: 'DGX A100',
    cpu_specs: '2x AMD EPYC 7742 (128 cores)',
    memory_specs: '1TB DDR4',
    storage_specs: '16x 3.8TB NVMe SSD',
    ip_address: '10.1.2.101',
    mac_address: 'bb:cc:dd:ee:ff:02',
    vlan_id: 400,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 40.0,
    memory_baseline: 70.0,
    temp_idle: 45.0,
    power_idle: 800,
  },

  // Rack RBT-B2 Servers
  {
    id: 'RBT-B2-S001',
    name: 'storage-server-01',
    rack_id: 'RBT-B2',
    position: 'U1-U4',
    server_type: 'Storage Server',
    operating_system: 'TrueNAS SCALE',
    brand: 'Supermicro',
    model: 'SuperStorage 6049P-E1CR24L',
    cpu_specs: 'Intel Xeon Gold 6248R (24 cores)',
    memory_specs: '256 GB DDR4',
    storage_specs: '24x 8TB SATA',
    ip_address: '10.1.2.102',
    mac_address: 'bb:cc:dd:ee:ff:03',
    vlan_id: 500,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 15.0,
    memory_baseline: 45.0,
    temp_idle: 38.0,
    power_idle: 280,
  },
  {
    id: 'RBT-B2-S002',
    name: 'nas-server-02',
    rack_id: 'RBT-B2',
    position: 'U5-U8',
    server_type: 'NAS Server',
    operating_system: 'FreeNAS',
    brand: 'QNAP',
    model: 'TS-2483XU-RP',
    cpu_specs: 'Intel Xeon D-1548 (8 cores)',
    memory_specs: '128 GB DDR4',
    storage_specs: '24x 6TB NAS',
    ip_address: '10.1.2.103',
    mac_address: 'bb:cc:dd:ee:ff:04',
    vlan_id: 500,
    status: ServerStatus.ERROR,
    cpu_baseline: 10.0,
    memory_baseline: 30.0,
    temp_idle: 35.0,
    power_idle: 200,
  },

  // Rack RBT-C1 Servers
  {
    id: 'RBT-C1-S001',
    name: 'kubernetes-master-01',
    rack_id: 'RBT-C1',
    position: 'U1-U2',
    server_type: 'Kubernetes Master',
    operating_system: 'Ubuntu 22.04 LTS',
    brand: 'Dell',
    model: 'PowerEdge R650',
    cpu_specs: 'Intel Xeon Gold 6338 (32 cores)',
    memory_specs: '128 GB DDR4',
    storage_specs: '4x 1TB NVMe SSD',
    ip_address: '10.1.3.100',
    mac_address: 'cc:dd:ee:ff:aa:01',
    vlan_id: 600,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 30.0,
    memory_baseline: 65.0,
    temp_idle: 35.0,
    power_idle: 180,
  },
  {
    id: 'RBT-C1-S002',
    name: 'kubernetes-worker-01',
    rack_id: 'RBT-C1',
    position: 'U3-U4',
    server_type: 'Kubernetes Worker',
    operating_system: 'Ubuntu 22.04 LTS',
    brand: 'Dell',
    model: 'PowerEdge R650',
    cpu_specs: 'Intel Xeon Gold 6338 (32 cores)',
    memory_specs: '256 GB DDR4',
    storage_specs: '6x 1TB NVMe SSD',
    ip_address: '10.1.3.101',
    mac_address: 'cc:dd:ee:ff:aa:02',
    vlan_id: 600,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 50.0,
    memory_baseline: 80.0,
    temp_idle: 37.0,
    power_idle: 210,
  },
  {
    id: 'RBT-C1-S003',
    name: 'kubernetes-worker-02',
    rack_id: 'RBT-C1',
    position: 'U5-U6',
    server_type: 'Kubernetes Worker',
    operating_system: 'Ubuntu 22.04 LTS',
    brand: 'Dell',
    model: 'PowerEdge R650',
    cpu_specs: 'Intel Xeon Gold 6338 (32 cores)',
    memory_specs: '256 GB DDR4',
    storage_specs: '6x 1TB NVMe SSD',
    ip_address: '10.1.3.102',
    mac_address: 'cc:dd:ee:ff:aa:03',
    vlan_id: 600,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 45.0,
    memory_baseline: 75.0,
    temp_idle: 36.0,
    power_idle: 205,
  },

  // Rack RBT-C2 Servers
  {
    id: 'RBT-C2-S001',
    name: 'mail-server-prod-01',
    rack_id: 'RBT-C2',
    position: 'U1-U2',
    server_type: 'Mail Server',
    operating_system: 'CentOS Stream 9',
    brand: 'HP',
    model: 'ProLiant DL380 Gen10 Plus',
    cpu_specs: 'Intel Xeon Silver 4316 (20 cores)',
    memory_specs: '96 GB DDR4',
    storage_specs: '4x 2TB SATA',
    ip_address: '10.1.3.103',
    mac_address: 'cc:dd:ee:ff:aa:04',
    vlan_id: 700,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 20.0,
    memory_baseline: 55.0,
    temp_idle: 33.0,
    power_idle: 160,
  },
  {
    id: 'RBT-C2-S002',
    name: 'proxy-server-01',
    rack_id: 'RBT-C2',
    position: 'U3-U4',
    server_type: 'Proxy Server',
    operating_system: 'Ubuntu 22.04 LTS',
    brand: 'Dell',
    model: 'PowerEdge R440',
    cpu_specs: 'Intel Xeon Silver 4210R (10 cores)',
    memory_specs: '32 GB DDR4',
    storage_specs: '2x 500GB NVMe SSD',
    ip_address: '10.1.3.104',
    mac_address: 'cc:dd:ee:ff:aa:05',
    vlan_id: 700,
    status: ServerStatus.OFFLINE,
    cpu_baseline: 15.0,
    memory_baseline: 40.0,
    temp_idle: 30.0,
    power_idle: 120,
  },

  // Rack RBT-C3 Servers
  {
    id: 'RBT-C3-S001',
    name: 'test-server-01',
    rack_id: 'RBT-C3',
    position: 'U1-U2',
    server_type: 'Test Server',
    operating_system: 'Ubuntu 22.04 LTS',
    brand: 'Dell',
    model: 'PowerEdge R550',
    cpu_specs: 'Intel Xeon Silver 4316 (20 cores)',
    memory_specs: '64 GB DDR4',
    storage_specs: '2x 1TB NVMe SSD',
    ip_address: '10.1.3.105',
    mac_address: 'cc:dd:ee:ff:aa:06',
    vlan_id: 800,
    status: ServerStatus.MAINTENANCE,
    cpu_baseline: 25.0,
    memory_baseline: 50.0,
    temp_idle: 32.0,
    power_idle: 140,
  },
  {
    id: 'RBT-C3-S002',
    name: 'dev-server-01',
    rack_id: 'RBT-C3',
    position: 'U3-U4',
    server_type: 'Development Server',
    operating_system: 'Ubuntu 20.04 LTS',
    brand: 'HP',
    model: 'ProLiant DL360 Gen10 Plus',
    cpu_specs: 'Intel Xeon Gold 6226R (16 cores)',
    memory_specs: '128 GB DDR4',
    storage_specs: '4x 1TB NVMe SSD',
    ip_address: '10.1.3.106',
    mac_address: 'cc:dd:ee:ff:aa:07',
    vlan_id: 800,
    status: ServerStatus.ACTIVE,
    cpu_baseline: 30.0,
    memory_baseline: 60.0,
    temp_idle: 34.0,
    power_idle: 165,
  },
];